# Generated by Django 4.1.2 on 2023-04-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutEMS', models.TextField()),
                ('Source1', models.TextField()),
                ('Source2', models.TextField()),
                ('Source3', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='working',
            field=models.BooleanField(default=False),
        ),
    ]
