# Generated by Django 4.1.2 on 2023-04-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeMS', '0002_aboutmodel_alter_employee_working'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='Source1',
            new_name='SourceAbout',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='Source2',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='Source3',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='SourceName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
