# Generated by Django 4.1.2 on 2023-04-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeMS', '0003_rename_source1_aboutmodel_sourceabout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='SourceAbout',
            new_name='SourceAbout1',
        ),
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='SourceName',
            new_name='SourceName1',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='SourceAbout2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='SourceAbout3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='SourceName2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='SourceName3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
